name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 15 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install IBM CLI
      run: curl -sL https://raw.githubusercontent.com/IBM-Bluemix/developer-tools-installer/master/linux-installer/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
        ibmcloud login -u ${{ secrets.MAIL }} -p ${{ secrets.PWD }} -r ${{ secrets.RGN }}
    - name: Restart
      run: |
        ibmcloud target -g Default
        ibmcloud target --cf
        ibmcloud cf install
        ibmcloud login -a 'https://cloud.ibm.com' -r 'us-south'
        ibmcloud target --cf-api 'https://api.us-south.cf.cloud.ibm.com'
        ibmcloud cf restart ${{ secrets.CFNAME }}
